# Generated by Django 5.0 on 2023-12-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
    ]
